
/* Inserindo cidades */

INSERT INTO cidades values
	(null, "Recife"),
    (null, "Fortaleza"),
    (null, "Salvador");


/* Inserindo dados Tabela Eventos*/
 /*id;nome;urlfoto;hora;descricao;duracao;endereco;percurso*/
    
        
INSERT INTO eventos values
   
 (null, "Praça Marco Zero", "https://i.ibb.co/6XMWT1T/Rectangle-7.png", "9:00", "O Marco Zero, na Praça Rio Branco, é conhecido como local de fundação da cidade do Recife e também como ponto inicial de contagem das distâncias calculadas a partir da cidade. O lugar é um dos pontos mais importantes na capital Pernambucana, pois é também uma região de forte movimento durante o Carnaval. 
     Aproveite sua visita para tirar uma foto com os dois marcos (o antigo e o novo), observar a vista para o Parque de Esculturas e os edifícios do Centro Cultural da Caixa e da Associação Comercial de Pernambuco.
     Se quiser fazer compras, vale a pena visitar o novo Mercado de Artesanato, que também fica no local.", "Duração: 1h", "Endereço: Praça Rio Branco, Recife Antigo, Recife - PE", "3 min"),

 (null, "Paço do Frevo", "https://i.ibb.co/0Bjdmzq/Rectangle-7-1.png", "10:00", "O Paço do Frevo é um centro de referência de ações, projetos e atividades de documentação, transmissão, salvaguarda e valorização de uma das principais tradições culturais brasileiras, reconhecida como Patrimônio Imaterial da Humanidade pela Unesco: o frevo. Um lugar para estudar, criar, experimentar e vivenciar o rico universo de histórias, personalidades, memórias e linguagens artísticas.
     Localizado no Bairro do Recife, o Paço tem curadoria assinada por Bia Lessa. Além de se valer de conteúdos e linguagens diversas para manter vivo o ritmo que embalou a formação da identidade cultural recifense, 
     o equipamento promove oficinas e apresentações musicais regulares em quatro pavimentos de atividades, que oferecem aos visitantes a possibilidade de experimentar o Carnaval recifense durante todo o ano.", "Duração: 1h", 
     "Endereço: Praça do Arsenal da Marinha, s/n, Recife Antigo, Recife - PE", "2 min"),

 (null, "Rua do Bom Jesus","https://i.ibb.co/H4Xw8c9/Rectangle-7-2.png", "11:00", "A Rua do Bom Jesus, antiga Rua dos Judeus, é uma das mais importantes do Recife. Ela é pequena, cheia de edifícios antigos e coloridos, entre eles um casarão onde foi construída uma das primeiras sinagogas das Américas.
      Aos domingos acontece uma feira de artesanato que torna a rua ainda mais interessante.
      Não é um shopping grande e com muita variedade de lojas; possui uma praça de alimentação pequena, mas se destaca pelo ambiente intimista e aconchegante. É um shopping legal para fazer a pausa do almoço.", "Duração: 3h30min", "Endereço: Rua Bom Jesus, Recife Antigo, Recife - PE", "5 min"),
 (null, "Embaixada dos Bonecos Gigantes", "https://i.ibb.co/7SwLZDK/Rectangle-7-3.png", "15:00", "Quem perdeu o Carnaval de Recife e Olinda e não conseguiu ver os bonecos gigantes em ação não precisa ficar triste! A Embaixada dos Bonecos Gigantes expõe os famosos bonecos criados para participar do Carnaval nas duas cidades, permitindo que os turistas tenham uma clara ideia da dimensão, da estrutura e do modo de criação dos personagens. Os bonecos pesados e bem trabalhados representam personalidades variadas, personagens de desenhos e figuras brasileiras que se destacam ao longo do ano. 
       Adultos R$ 10,00 (Dez reais) |Criança (com até 12 anos) acompanhada por adulto pagante, entra sem pagar
       Horário de Funcionamento: Segunda a Domingo das 08:00h às 18:00h.
       Abre nos feriados exceto: Carnaval (sábado até a terça), 25 de dezembro e 01 de janeiro.", "Duração: 1h30min", "Endereço: Rua Bom Jesus, 183, Recife Antigo, Recife - PE", "5 min"),

 (null, "Rua da Moeda", "https://i.ibb.co/44zHD1Z/Rectangle-7-4.png", "16:00", "A Rua da Moeda é uma das mais conhecidas do Recife Antigo, popular entre os jovens por aglomerar vários bares legais na mesma região. Para quem quer fazer um happy hour ou encontrar os amigos, os bares da rua são boas opções.
        O lugar também recebe apresentações musicais, inclusive nas prévias do Carnaval. 
        Que tal finalizar o dia com drinks e petiscos locais?", "Duração:1h30min", "Endereço: Rua da Moeda, Recife Antigo, Recife - PE", "null"),
 (null, "Paço Alfândega","https://i.ibb.co/mJ9LhHQ/Rectangle-7-11.png", "9:00", "O Paço Alfândega já foi convento e alfândega do Recife e hoje em dia é um dos shoppings mais charmosos da cidade. Seu interior ainda conserva um misto de estrutura rústica e moderna, relembrando as origens do edifício do século XVIII. 
       Um lugar super bacana para sentar e tomar um café da manhã.", "Duração:2h", "Endereço: Rua da Alfândega, 35 , Recife Antigo, Recife - PE", "8 min"),
  
 (null, "Capela Dourada", "https://i.ibb.co/1rZ2BKx/Rectangle-7-10.png", "11:00", "A Capela Dourada é uma das igrejas mais bonitas do Recife e simboliza toda a riqueza do período colonial no Brasil. Construída entre os séculos XVII e XVIII, ela fica dentro do Convento e Igreja de Santo Antônio, que também abriga um Museu de Arte Sacra.
        A capela é riquíssima em detalhes de ouro; para onde quer que se olhe o brilho amarelo que envolve as madeiras talhadas nas paredes é surpreendente. Imagens e pinturas sacras complementam o conjunto visual da capela, que impressiona pela enorme quantidade de ouro empregada em suas paredes e pelo trabalho esculpido à mão. 
        Entrada: R$ 3.", "Duração:1h", "Endereço: R. Imperador Dom Pedro II, Santo Antônio, Recife - PE", "10 min"),
 (null, "Restaurante Leite", "https://i.ibb.co/SP3FbxN/Rectangle-7-9.png", "12:00", "Fundado em 1882, o Leite é o restaurante mais antigo do Recife, quiçá o mais antigo do Brasil. Seu ambiente é refinado, com direito a luz baixa e um piano com músicas de qualidade tocadas como plano de fundo. É um lugar mais indicado para ocasiões especiais e uma refeição sofisticada, pois o valor não é muito camarada. Tem garçons muito atenciosos, que se vestem tradicionalmente de branco há vários anos. Sua decoração sofreu várias mudanças ao longo dos anos; o lugar teve de se modernizar, mas manteve a essência de servir pratos saborosos para uma clientela que busca uma refeição rebuscada. 
        É um lugar para ir sem pressa e aproveitar a atmosfera. 
        O bacalhau e os camarões são boas pedidas, mas há também outras opções.", "Duração:2h", "Endereço: Praça Joaquim Nabuco, 147 , Santo Antônio, Recife - PE", "10 min"),

 (null, "Mercado de São José", "https://i.ibb.co/zXcvnk9/Rectangle-7-7.png", "14:30", "O Mercado São José fica numa região popular e movimentada, e quem procura artesanato ou produtos pernambucanos tem neste local uma das melhores opções da cidade. Nele você poderá encontrar um pouco de tudo: peixes e mariscos frescos, artigos em couro, ímãs, tecidos rendados, enfeites em madeira, lembranças da cidade e outros produtos do artesanato local.
        A vantagem de visitar o Mercado São José é que ele agrupa uma grande variedade de lojas, permitindo ao turista encontrar um pouco de tudo no mesmo lugar.
        Ao redor do Mercado ficam muitas lojas populares e camelôs - quem quer comprar produtos com preços baixos pode circular pela região. ", "Duração:1h30min", "Endereço: Praça Don Vital, s/nº, São José, Recife - PE", "11 min"),
   
   
   
 (null, "Casa da Cultura", "https://i.ibb.co/wBB39MT/Rectangle-7-6.png", "17:00", "A Casa da Cultura é um antigo presídio recifense, desativado há cerca de 40 anos, que hoje funciona como ponto turístico. O local, construído a partir do princípio panóptico, foi revitalizado e agora abriga lojinhas de artesanato e escritórios. É um ponto de parada muito interessante para tirar fotos, observar a arquitetura e, principalmente, fazer algumas comprinhas. Nesse local é possível encontrar lojinhas que vendem castanhas, tecidos, artigos de decoração, roupas etc. 
        Cada cela tornou-se uma loja, mas quem quiser ver como era uma cela original poderá encontrar uma cela vazia no raio leste. Outra dica é subir no segundo andar do presídio pelo raio norte, onde há um ponto de observação para possíveis revoltas. ", "Duração:1h30min", "Endereço: R. Floriano Peixoto, 905, Santo Antônio, Recife - PE", "15 min"),  
 (null, "Passeio Noturno de Catamarã", "https://i.ibb.co/hfQmt6j/Rectangle-7-5.png", "19:00", "Ao som de frevo e outras pernambucanidades, o catamarã passa por edifícios históricos como o Ginásio Pernambucano, a Assembleia Legislativa e a parte de trás do Palácio do Campo das Princesas, e tem a opção mais famosa: o tour Recife e Suas Pontes, que percorre as três ilhas do Centro.
        Durante o percurso, um guia vai contando curiosidades sobre a cidade e explicando a história por trás de cada ponte e de muitos dos prédios que são vistos desde o rio. O passeio funciona diariamente às 11h, 16h e 20h e no fim de semana também às 14h30 e 17h30. A saída é a partir do restaurante Catamaran, no bairro de São José, e você pode comprar o ingresso (que custa R$ 45 pra adultos e R$ 25 pra crianças de 6 a 10 anos) online ou na hora mesmo.", "Duração:1h30min", "Endereço: Saída do Cais das Cinco Pontas, Recife - PE", "null"),  
 (null, "Praia do Pina", "https://i.ibb.co/BzCqtzN/Rectangle-7-12.png", "9:00", "A Praia do Pina é uma praia popular do Recife, com longa faixa de areia, coqueiros na orla e mar verdinho, típico da região. É um lugar bastante frequentado por moradores da cidade, com quiosques e barracas, mas fiquem atentos aos sinais na areia de tubarões. 
        Ela é uma continuação da praia Boa Viagem e pode ser uma boa opção para curtir o mar num dia de sol. Uma das boas vantagens do Recife é que as águas do mar tem temperatura agradável e não causam aquele choque térmico na hora do mergulho. ", "Duração:4h", "Endereço: Pina, Recife - PE", "3 min"),  
 (null, "Tasquinha do Tio", "https://i.ibb.co/vQcB4zD/Rectangle-7-13.png", "13:30", "Restaurante português à beira mar, ideal para almoçar, de frente para a praia, com um clima agradável e comida excelente. Além da comida impecável, esse queridinho dos famosos tem drinks locais e muito criativos para refrescar o seu dia.", "Duração:1h30min", "Endereço: Av. Boa Viagem, 560 - Pina, Recife - PE", "25 min"),  
 (null, "Shopping RioMar", "https://i.ibb.co/BC2fdQ3/Rectangle-7-14.png", "15:00", "O Shopping Rio Mar é o mais novo do Recife e um dos maiores do Brasil. Nele é possível encontrar uma grande variedade de lojas de marcas brasileiras e estrangeiras, além de restaurantes e serviços. ", "Duração:3h", "Endereço: Avenida República do Líbano, 251, Pina, Recife - PE", "10 min"),  
 (null, "Galeria Joana D'Arc", "https://i.ibb.co/Mc6mHTs/Rectangle-7-15.png", "18:00", "A Galeria Joana D'arc ainda não é um lugar tão famoso no Recife, mas é uma opção bacana para conhecer à noite. O lugar tem algumas lojas e restaurantes, e fica cheio aos finais de semana. Por lá você encontrará restaurantes de comida italiana, mexicana e uma das melhores creperias da cidade. A facilidade dessa galeria é agrupar restaurantes variados no mesmo local, agradando pessoas de diversos gostos e idades.", "Duração:4h", "Endereço: Av. Herculano Bandeira, 513, Pina, Recife - PE", "10 min"),  
 (null, "Restaurante Bargaço", "https://i.ibb.co/nrBPvz6/Rectangle-7-16.png", "19:30", "Nada como finalizar a viagem com um dos melhores restaurantes de Recife. o Bargaço iniciou o que seria o marco da comida baiana e frutos do mar no Brasil. Sua história começou há 37 anos, quando o pernambucano da cidade de Limoeiro Leonel Evaristo da Rocha chegou à Bahia em 1968 para trabalhar. ", "Duração:2h", "Endereço: Av. Engenheiro Antônio de Góes, 62, Pina, Recife - PE", "null"),  
 (null, "Praia de Muro Alto", "https://i.ibb.co/KVhwgVc/Rectangle-7-17.png", "10:00", "A Praia de Muro Alto é uma das mais famosas da região. Localizada a aproximadamente 8 km da praia de Porto de Galinhas, ela possui águas mornas, rasas e cristalinas, atraindo turistas de diversas regiões do país.
        Também é a praia preferida dos amantes de corrida, pois a areia mais próxima do mar é firme o suficiente para correr 5km ou 10k e não causar dor nas panturrilhas dos corredores.
        Muitos visitantes afirmam ser uma praia perfeita, com piscinas naturais que tornam o passeio ideal para crianças. Excelente para passar horas apenas admirando a paisagem, essa é a praia certa para quem busca águas tranquilas.", "Duração:2h", "null","25min"),
 (null, "Piscinas Naturais de Porto de Galinhas", "https://i.ibb.co/t4PvNRn/Rectangle-7-18.png", "13:00", "As piscinas naturais de Porto de Galinhas permitem que essa seja uma das praias mais famosas do Brasil. Com sua beleza paradisíaca, as águas azuis e calmas marcam o local, já que é possível até mesmo observar os peixes que vivem ali.
        A paisagem das piscinas naturais é surpreendente e encantadora. O passeio é inesquecível e um dos locais mais belos que os visitantes já viram.", "Duração:3h", "null", "10 min"),  
 (null, "Pontal de Maracaípe", "https://i.ibb.co/StQPrg1/Rectangle-7-19.png", "16:00", "O Pontal de Maracaípe é o local onde acontece o encontro entre as águas do rios e do mar. Devido ao acesso ser restrito apenas para quem vai a pé ou de bugue, o Pontal de Maracaípe é mais vazio que as praias da região, e tão lindo quanto.
        O passeio de jangada na região é muito indicado por visitantes, especialmente durante o pôr do sol, para uma experiência ainda mais surpreendente.", "Duração:2h", "null", "1h20min"),  
 (null, "Praia de Carneiros e suas Piscinas Naturais", "https://i.ibb.co/34X1XF1/Rectangle-7-20.png", "10:00", "Praia dos Carneiros, uma das mais belas do Brasil. Além disso, contém piscinas naturais que se formam entre os corais.Para conseguir curtir um momento tão especial de encontro com os habitantes do mar, não se esqueça de verificar a tábua de marés do dia. Quanto mais próximo o indicador estiver do zero, mais baixa a altura da água e melhor para visualizar os arrecifes. 
        Ao entrar nas piscinas, observe os peixinhos ao redor e os corais, que parecem ainda mais reais embaixo de águas cristalinas. As crianças vão achar o máximo! Afinal, além de poderem ver de perto a vida marinha, também vão aproveitar a tranquilidade de uma praia sem ondas, perfeita e segura para banho. Só vale tomar cuidado para não pisar nos corais, que podem machucar os pés.", "Duração:3h", "null", "5 min"), 
 (null, "Restaurante Bora Bora", "https://i.ibb.co/LQMzpV9/Rectangle-7-21.png", "13:00", "Uma pausa para petiscar e curtir uma boa comida. Entre coqueiros, espreguiçadeiras de frente para o mar, redes para descanso, chuveirões e parquinho para as crianças, um cardápio recheado de frutos do mar saborosos como o Camarão Bora Bora. O carro-chefe da casa é preparado aos quatro queijos e servido em coco verde.", "Duração:2h", "null", "30 min"), 
 (null, "Capela de São Benedito", "https://i.ibb.co/fN7X4MD/Rectangle-7-22.png", "15:00", "Que tal uma caminhada para explorar cada detalhe da Praia dos Carneiros a pé? Areias fofas e claras são acompanhadas por coqueiros altos e verdes. No mar calmo e de águas cristalinas, passeiam catamarãs, pequenos barcos e lanchas. Siga caminhando até avistar uma pequena igreja com as portas viradas para o mar e muitos coqueiros ao fundo. É a Capela de São Benedito, construída no século 18. A vista dela é incrível!", "Duração:30min", "null", "1 min"), 
 (null, "Praia de Carneiros com Pôr do Sol", "https://i.ibb.co/cDLmRmq/Rectangle-7-24.png", "15:30", "Que tal uma caminhada para explorar cada detalhe da Praia dos Carneiros a pé? Areias fofas e claras são acompanhadas por coqueiros altos e verdes. No mar calmo e de águas cristalinas, passeiam catamarãs, pequenos barcos e lanchas. Siga caminhando até avistar uma pequena igreja com as portas viradas para o mar e muitos coqueiros ao fundo. É a Capela de São Benedito, construída no século 18. A vista dela é incrível!", "Duração:2h", "null", "1h50 min"),
 (null, "Praia de Barra Grande", "https://i.ibb.co/kDqnzVS/Rectangle-7-27.png", "10:30", "Espere encontrar águas de azul clarinho e orlas cercadas por coqueirais extensos. Mantendo a estrutura turística diversa, a Praia de Barra Grande concentra o agito do litoral de Maragogi.", "Duração:3h", "null", "5 min"), 
 (null, "Piscinas Naturais de Barra Grande", "https://i.ibb.co/V9PZnYp/Rectangle-7-26.png", "13:30", "Piscinas naturais localizadas na praia de Barra Grande, perfeitas para famílias e relaxar. Contam com águas perfeitas para mergulhar, de temperaturas agradáveis e repletas de peixes. 
        O passeio pelas piscinas naturais de Maragogi é feito apenas em época de maré baixa, já que com a maré alta as piscinas se tornam mais profundas e com águas menos cristalinas, dificultando o mergulho.", "Duração:2h", "null", "15 min"), 
 (null, "Povoado de São Bento", "https://i.ibb.co/cx7WX46/Rectangle-7-25.png", "15:00", "Além de abrigar a lindíssima Praia de São Bento, o Povoado de São Bento conta com atrações históricas e lugares ideais para curtir um ritmo de sossegado. 
        Com uma atmosfera bucólica e pacata, o povoado é famoso por produzir os deliciosos bolos de goma, que são biscoitos feitos com coco. 
        Por lá, não deixe de conhecer também as ruínas da Igreja de São Bento, que compõem um importantíssimo patrimônio histórico da região.  
        E, para aproveitar a visita, passe também pelas ruínas do Mosteiro de São Bento, com arquitetura típica do período colonial, datada do século XVII.", "Duração:2h30min", "null", "2h30 min"), 
 (null, "Mosteiro de São Bento", "https://i.ibb.co/0VQpsYb/Rectangle-7-28.png", "13:30", "Ao fazer um roteiro pelo Centro Histórico de Olinda, o Mosteiro de São Bento é um dos locais que você não pode deixar de conhecer. A obra de estilo barroco, fundada entre 1586 e 1592, destaca-se entre as demais por possuir  um belo conjunto arquitetônico, que inclui pinturas e um trabalho muito detalhado em ouro - os guias locais chegam a afirmar que no interior do Mosteiro foram utilizados cerca de 100kg de ouro. O altar tem mais de 12m e é realmente espetacular, todo feito em madeira e revestido em ouro. Imperdível!

        Se puder, faça sua visita às 10h, no domingo, que é quando se pode admirar o canto gregoriano. 
        Entrada gratuita. ", "Duração:2h", "Endereço: Rua de São Bento, s/n, Olinda - PE", "5 min"),
 (null, "Igreja do Carmo", "https://i.ibb.co/vH7zv0D/Rectangle-7-29.png", "11:00", "A Igreja do Carmo, com construção iniciada em 1580, é uma das obras mais simbólicas de Olinda. Estrategicamente construída no alto de um morro, foi a primeira igreja da Ordem dos Carmelitas na América Latina. 
        Depois de um longo período fechada para reformas, a igreja oferece visitas gratuitas aos turistas, que podem admirar os dois altares, feitos em madeira entalhada e pintados com ouro. No geral, a arquitetura da igreja é bastante simples - os detalhes minuciosos dos altares é que chamam a atenção.", "Duração:2h", "Endereço: Praça do Carmo, s/n, Olinda - PE", "7 min"), 
 (null, "Convento de São Francisco", "https://i.ibb.co/2WBF4zR/Rectangle-7-30.png", "13:00", "O Convento de São Francisco, datado de 1585, faz parte de um conjunto arquitetônico que inclui a Igreja de Nossa Senhora das Neves, a Capela de Santana e a Capela de São Roque. 
        Na propriedade, que tem vários ambientes, chamam a atenção os trabalhos feitos em madeira, as pinturas e, principalmente, os azulejos portugueses que retratam a vida de Francisco de Assis. O local merece uma reforma, pois não está tão bem conservado, mas vale a visita.
        Entrada: R$ 3.", "Duração:2h", "Endereço: Rua de São Francisco, 280, Olinda - PE", "5 min"), 
 (null, "Alto da Sé", "https://i.ibb.co/gJ28JSy/Rectangle-7-31.png", "15:00", "O Alto da Sé é uma região de Olinda muito visitada por turistas. Nesse local concentram-se alguns pontos turísticos - como o Elevador Panorâmico e a Igreja da Sé -, além de lojinhas e barracas que vendem artesanato. Para quem quer chegar ao Alto da Sé, é mais vantagem subir pela Rua São Francisco, que tem uma ladeira menos íngreme do que a rua da Ladeira da Misericórdia.
        É um lugar legal para encontrar artesanato, quadros, lembranças etc. ", "Duração:2h", "Endereço: Alto da Sé, Olinda - PE", "10 min"), 
 (null, "Museu de Arte Contemporânea", "https://i.ibb.co/yYtngT4/Rectangle-7-32.png", "17:00", "Uma das cidades mais antigas do Brasil, listada como Patrimônio Histórico pela Unesco, Olinda dá grande importância a seus museus.
        O Museu de Arte Contemporânea, no centro histórico, funciona na antiga sede do Aljube da Diocese de Olinda. O Museu de Arte Sacra de Pernambuco, por sua vez, está instalado em um edifício histórico, um dos primeiros construídos na cidade.", "Duração:2h", "Endereço: R. Treze de Maio, 149 - Carmo, Olinda - PE", "10 min");
